-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_bn_act_pool_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Y_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    Y_ce0 : OUT STD_LOGIC;
    Y_we0 : OUT STD_LOGIC;
    Y_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    Y_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    U_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    U_ce0 : OUT STD_LOGIC;
    U_we0 : OUT STD_LOGIC;
    U_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of conv_bn_act_pool_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000001000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000010000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state57 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000100000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state58 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000001000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state59 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000010000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state60 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000100000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state61 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000001000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state62 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000010000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state63 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000100000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state64 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000001000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state65 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000010000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state66 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000100000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state67 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000001000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state68 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000010000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state69 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000100000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state70 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000001000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state71 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000010000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state72 : STD_LOGIC_VECTOR (82 downto 0) := "00000000000100000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state73 : STD_LOGIC_VECTOR (82 downto 0) := "00000000001000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state74 : STD_LOGIC_VECTOR (82 downto 0) := "00000000010000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state75 : STD_LOGIC_VECTOR (82 downto 0) := "00000000100000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state76 : STD_LOGIC_VECTOR (82 downto 0) := "00000001000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state77 : STD_LOGIC_VECTOR (82 downto 0) := "00000010000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state78 : STD_LOGIC_VECTOR (82 downto 0) := "00000100000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state79 : STD_LOGIC_VECTOR (82 downto 0) := "00001000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state80 : STD_LOGIC_VECTOR (82 downto 0) := "00010000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state81 : STD_LOGIC_VECTOR (82 downto 0) := "00100000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state82 : STD_LOGIC_VECTOR (82 downto 0) := "01000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state83 : STD_LOGIC_VECTOR (82 downto 0) := "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_4B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000011";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv32_45 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_51 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_52 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv16_1419 : STD_LOGIC_VECTOR (15 downto 0) := "0001010000011001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv16_4200 : STD_LOGIC_VECTOR (15 downto 0) := "0100001000000000";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (82 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal X_slice_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal X_slice_ce0 : STD_LOGIC;
    signal X_slice_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ConvW0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal ConvW0_ce0 : STD_LOGIC;
    signal ConvW0_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal BN1_var0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal BN1_var0_ce0 : STD_LOGIC;
    signal BN1_var0_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal BN1_gamma0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal BN1_gamma0_ce0 : STD_LOGIC;
    signal BN1_gamma0_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_336_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_351 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state59 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state59 : signal is "none";
    signal grp_fu_328_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_357 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ap_CS_fsm_state64 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state64 : signal is "none";
    signal ap_CS_fsm_state76 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state76 : signal is "none";
    signal grp_fu_324_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_365 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal ap_CS_fsm_state37 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state37 : signal is "none";
    signal reg_371 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state36 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state36 : signal is "none";
    signal ap_CS_fsm_state71 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state71 : signal is "none";
    signal t_fu_383_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_reg_726 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal shl_ln_fu_389_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_reg_731 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln77_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln78_fu_397_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln78_reg_736 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal f_fu_407_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal f_reg_744 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln81_fu_413_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln81_reg_749 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln78_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_fu_423_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_reg_757 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal shl_ln7_fu_439_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln7_reg_762 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln81_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_fu_462_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_reg_770 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln84_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal X_slice_load_reg_785 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ConvW0_load_reg_790 : STD_LOGIC_VECTOR (15 downto 0);
    signal t_2_fu_512_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_2_reg_798 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal add_ln93_fu_538_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln93_reg_803 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln92_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_550_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_reg_811 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal add_ln95_fu_566_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln95_reg_816 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln94_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal BN1_var0_load_reg_831 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal BN1_gamma0_load_reg_836 : STD_LOGIC_VECTOR (15 downto 0);
    signal Y_addr_reg_841 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state35 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state35 : signal is "none";
    signal grp_fu_316_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_83_reg_846 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_312_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_84_reg_851 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state53 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state53 : signal is "none";
    signal grp_fu_321_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal nrm_reg_856 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state55 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state55 : signal is "none";
    signal select_ln46_fu_575_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln46_reg_861 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state66 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state66 : signal is "none";
    signal u_fu_593_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal u_reg_869 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state68 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state68 : signal is "none";
    signal zext_ln106_1_fu_607_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln106_1_reg_874 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln103_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln106_fu_611_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln106_reg_879 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln6_fu_617_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln6_reg_884 : STD_LOGIC_VECTOR (8 downto 0);
    signal c_1_cast4_fu_625_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal c_1_cast4_reg_889 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state69 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state69 : signal is "none";
    signal c_1_cast_fu_629_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal c_1_cast_reg_894 : STD_LOGIC_VECTOR (8 downto 0);
    signal c_6_fu_639_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_6_reg_902 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_fu_655_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_reg_910 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state70 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state70 : signal is "none";
    signal icmp_ln106_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln107_fu_714_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln107_reg_920 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_340_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_88_reg_925 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state82 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state82 : signal is "none";
    signal t_0_reg_174 : STD_LOGIC_VECTOR (5 downto 0);
    signal f_0_reg_186 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_0_reg_197 : STD_LOGIC_VECTOR (15 downto 0);
    signal k_0_reg_210 : STD_LOGIC_VECTOR (2 downto 0);
    signal acc_1_reg_222 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_0_reg_234 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_1_reg_245 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_0_reg_256 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state67 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state67 : signal is "none";
    signal u_0_reg_267 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln104_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_1_reg_278 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state83 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state83 : signal is "none";
    signal acc_2_reg_289 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_reg_301 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln88_fu_451_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_1_fu_477_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_2_fu_501_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln95_fu_556_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln95_2_fu_571_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln106_fu_701_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln107_fu_719_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal ap_CS_fsm_state54 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state54 : signal is "none";
    signal grp_fu_324_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal grp_fu_328_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_328_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state60 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state60 : signal is "none";
    signal ap_CS_fsm_state72 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state72 : signal is "none";
    signal grp_fu_336_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_336_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state56 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state56 : signal is "none";
    signal ap_CS_fsm_state65 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state65 : signal is "none";
    signal zext_ln82_fu_429_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln82_fu_433_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln88_fu_447_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln85_fu_468_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln85_fu_472_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln85_fu_482_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_486_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln85_1_fu_496_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln93_1_fu_526_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln93_fu_534_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln4_fu_518_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln95_1_fu_562_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln5_fu_599_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal u_0_cast5_fu_583_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_0_cast_fu_645_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln106_fu_661_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln106_2_fu_674_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln106_2_fu_682_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln106_1_fu_666_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln106_fu_687_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln106_1_fu_691_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln106_1_fu_697_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln107_1_fu_706_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln107_1_fu_710_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (82 downto 0);

    component main_fdiv_32ns_32ns_32_16_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_fsqrt_32ns_32ns_32_12_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_sptohp_32ns_16_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component main_hptosp_16ns_32_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_hadd_16ns_16ns_16_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component main_hmul_16ns_16ns_16_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component main_hdiv_16ns_16ns_16_7_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component main_hcmp_16ns_16ns_1_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component conv_bn_act_pool_4_X_slice IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component conv_bn_act_pool_4_ConvW0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component conv_bn_act_pool_4_BN1_var0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    X_slice_U : component conv_bn_act_pool_4_X_slice
    generic map (
        DataWidth => 16,
        AddressRange => 1344,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => X_slice_address0,
        ce0 => X_slice_ce0,
        q0 => X_slice_q0);

    ConvW0_U : component conv_bn_act_pool_4_ConvW0
    generic map (
        DataWidth => 16,
        AddressRange => 7168,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ConvW0_address0,
        ce0 => ConvW0_ce0,
        q0 => ConvW0_q0);

    BN1_var0_U : component conv_bn_act_pool_4_BN1_var0
    generic map (
        DataWidth => 16,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => BN1_var0_address0,
        ce0 => BN1_var0_ce0,
        q0 => BN1_var0_q0);

    BN1_gamma0_U : component conv_bn_act_pool_4_BN1_var0
    generic map (
        DataWidth => 16,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => BN1_gamma0_address0,
        ce0 => BN1_gamma0_ce0,
        q0 => BN1_gamma0_q0);

    main_fdiv_32ns_32ns_32_16_1_U1 : component main_fdiv_32ns_32ns_32_16_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_365,
        din1 => tmp_83_reg_846,
        ce => ap_const_logic_1,
        dout => grp_fu_312_p2);

    main_fsqrt_32ns_32ns_32_12_1_U2 : component main_fsqrt_32ns_32ns_32_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_0,
        din1 => reg_365,
        ce => ap_const_logic_1,
        dout => grp_fu_316_p2);

    main_sptohp_32ns_16_2_1_U3 : component main_sptohp_32ns_16_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_84_reg_851,
        ce => ap_const_logic_1,
        dout => grp_fu_321_p1);

    main_hptosp_16ns_32_2_1_U4 : component main_hptosp_16ns_32_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_324_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_324_p1);

    main_hadd_16ns_16ns_16_5_full_dsp_1_U5 : component main_hadd_16ns_16ns_16_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_328_p0,
        din1 => grp_fu_328_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_328_p2);

    main_hmul_16ns_16ns_16_4_max_dsp_1_U6 : component main_hmul_16ns_16ns_16_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_336_p0,
        din1 => grp_fu_336_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_336_p2);

    main_hdiv_16ns_16ns_16_7_1_U7 : component main_hdiv_16ns_16ns_16_7_1
    generic map (
        ID => 1,
        NUM_STAGE => 7,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_2_reg_289,
        din1 => ap_const_lv16_4200,
        ce => ap_const_logic_1,
        dout => grp_fu_340_p2);

    main_hcmp_16ns_16ns_1_2_1_U8 : component main_hcmp_16ns_16ns_1_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_357,
        din1 => ap_const_lv16_0,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_346_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    acc_0_reg_197_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln84_fu_456_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                acc_0_reg_197 <= acc_1_reg_222;
            elsif (((icmp_ln78_fu_401_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                acc_0_reg_197 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;

    acc_1_reg_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                acc_1_reg_222 <= grp_fu_328_p2;
            elsif (((icmp_ln81_fu_417_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                acc_1_reg_222 <= acc_0_reg_197;
            end if; 
        end if;
    end process;

    acc_2_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_633_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state69))) then 
                acc_2_reg_289 <= ap_const_lv16_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state76)) then 
                acc_2_reg_289 <= grp_fu_328_p2;
            end if; 
        end if;
    end process;

    c_0_reg_256_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state67)) then 
                c_0_reg_256 <= c_reg_811;
            elsif (((icmp_ln92_fu_506_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                c_0_reg_256 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    c_1_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln103_fu_587_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state68))) then 
                c_1_reg_278 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state83)) then 
                c_1_reg_278 <= c_6_reg_902;
            end if; 
        end if;
    end process;

    e_0_reg_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                e_0_reg_234 <= e_reg_770;
            elsif (((icmp_ln81_fu_417_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                e_0_reg_234 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    f_0_reg_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln77_fu_377_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                f_0_reg_186 <= ap_const_lv6_0;
            elsif (((icmp_ln81_fu_417_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                f_0_reg_186 <= f_reg_744;
            end if; 
        end if;
    end process;

    k_0_reg_210_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln84_fu_456_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                k_0_reg_210 <= k_reg_757;
            elsif (((icmp_ln78_fu_401_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                k_0_reg_210 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    p_0_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_633_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state69))) then 
                p_0_reg_301 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state76)) then 
                p_0_reg_301 <= p_reg_910;
            end if; 
        end if;
    end process;

    t_0_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln78_fu_401_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                t_0_reg_174 <= t_reg_726;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_0_reg_174 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    t_1_reg_245_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln77_fu_377_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_1_reg_245 <= ap_const_lv6_0;
            elsif (((icmp_ln94_fu_544_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                t_1_reg_245 <= t_2_reg_798;
            end if; 
        end if;
    end process;

    u_0_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln92_fu_506_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                u_0_reg_267 <= ap_const_lv4_0;
            elsif (((icmp_ln104_fu_633_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state69))) then 
                u_0_reg_267 <= u_reg_869;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                BN1_gamma0_load_reg_836 <= BN1_gamma0_q0;
                BN1_var0_load_reg_831 <= BN1_var0_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                ConvW0_load_reg_790 <= ConvW0_q0;
                X_slice_load_reg_785 <= X_slice_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state35)) then
                    Y_addr_reg_841(10 downto 0) <= zext_ln95_2_fu_571_p1(15 - 1 downto 0)(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln106_fu_649_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state70))) then
                add_ln107_reg_920 <= add_ln107_fu_714_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln92_fu_506_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    add_ln93_reg_803(10 downto 2) <= add_ln93_fu_538_p2(10 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln94_fu_544_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                add_ln95_reg_816 <= add_ln95_fu_566_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state69)) then
                    c_1_cast4_reg_889(5 downto 0) <= c_1_cast4_fu_625_p1(5 downto 0);
                    c_1_cast_reg_894(5 downto 0) <= c_1_cast_fu_629_p1(5 downto 0);
                c_6_reg_902 <= c_6_fu_639_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                c_reg_811 <= c_fu_550_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                e_reg_770 <= e_fu_462_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                f_reg_744 <= f_fu_407_p2;
                    zext_ln78_reg_736(5 downto 0) <= zext_ln78_fu_397_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                k_reg_757 <= k_fu_423_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state55)) then
                nrm_reg_856 <= grp_fu_321_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state70)) then
                p_reg_910 <= p_fu_655_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state59) or (ap_const_logic_1 = ap_CS_fsm_state10))) then
                reg_351 <= grp_fu_336_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state76) or (ap_const_logic_1 = ap_CS_fsm_state64) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state15))) then
                reg_357 <= grp_fu_328_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state37) or (ap_const_logic_1 = ap_CS_fsm_state25))) then
                reg_365 <= grp_fu_324_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state71) or (ap_const_logic_1 = ap_CS_fsm_state36))) then
                reg_371 <= Y_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state66)) then
                select_ln46_reg_861 <= select_ln46_fu_575_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln103_fu_587_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state68))) then
                    shl_ln6_reg_884(8 downto 5) <= shl_ln6_fu_617_p3(8 downto 5);
                sub_ln106_reg_879 <= sub_ln106_fu_611_p2;
                    zext_ln106_1_reg_874(5 downto 2) <= zext_ln106_1_fu_607_p1(5 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln81_fu_417_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    shl_ln7_reg_762(10 downto 5) <= shl_ln7_fu_439_p3(10 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln77_fu_377_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    shl_ln_reg_731(10 downto 5) <= shl_ln_fu_389_p3(10 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                t_2_reg_798 <= t_2_fu_512_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                t_reg_726 <= t_fu_383_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state37)) then
                tmp_83_reg_846 <= grp_fu_316_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state53)) then
                tmp_84_reg_851 <= grp_fu_312_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state82)) then
                tmp_88_reg_925 <= grp_fu_340_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state68)) then
                u_reg_869 <= u_fu_593_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln78_fu_401_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    zext_ln81_reg_749(5 downto 0) <= zext_ln81_fu_413_p1(5 downto 0);
            end if;
        end if;
    end process;
    shl_ln_reg_731(4 downto 0) <= "00000";
    zext_ln78_reg_736(10 downto 6) <= "00000";
    zext_ln81_reg_749(12 downto 6) <= "0000000";
    shl_ln7_reg_762(4 downto 0) <= "00000";
    add_ln93_reg_803(1 downto 0) <= "00";
    Y_addr_reg_841(14 downto 11) <= "0000";
    zext_ln106_1_reg_874(1 downto 0) <= "00";
    zext_ln106_1_reg_874(6) <= '0';
    shl_ln6_reg_884(4 downto 0) <= "00000";
    c_1_cast4_reg_889(6) <= '0';
    c_1_cast_reg_894(8 downto 6) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln77_fu_377_p2, ap_CS_fsm_state3, icmp_ln78_fu_401_p2, ap_CS_fsm_state4, icmp_ln81_fu_417_p2, ap_CS_fsm_state5, icmp_ln84_fu_456_p2, ap_CS_fsm_state16, icmp_ln92_fu_506_p2, ap_CS_fsm_state17, icmp_ln94_fu_544_p2, ap_CS_fsm_state68, icmp_ln103_fu_587_p2, ap_CS_fsm_state69, ap_CS_fsm_state70, icmp_ln106_fu_649_p2, icmp_ln104_fu_633_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln77_fu_377_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln78_fu_401_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln81_fu_417_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln84_fu_456_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state16 => 
                if (((icmp_ln92_fu_506_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state68;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state17 => 
                if (((icmp_ln94_fu_544_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state50;
            when ap_ST_fsm_state50 => 
                ap_NS_fsm <= ap_ST_fsm_state51;
            when ap_ST_fsm_state51 => 
                ap_NS_fsm <= ap_ST_fsm_state52;
            when ap_ST_fsm_state52 => 
                ap_NS_fsm <= ap_ST_fsm_state53;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                ap_NS_fsm <= ap_ST_fsm_state55;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state57;
            when ap_ST_fsm_state57 => 
                ap_NS_fsm <= ap_ST_fsm_state58;
            when ap_ST_fsm_state58 => 
                ap_NS_fsm <= ap_ST_fsm_state59;
            when ap_ST_fsm_state59 => 
                ap_NS_fsm <= ap_ST_fsm_state60;
            when ap_ST_fsm_state60 => 
                ap_NS_fsm <= ap_ST_fsm_state61;
            when ap_ST_fsm_state61 => 
                ap_NS_fsm <= ap_ST_fsm_state62;
            when ap_ST_fsm_state62 => 
                ap_NS_fsm <= ap_ST_fsm_state63;
            when ap_ST_fsm_state63 => 
                ap_NS_fsm <= ap_ST_fsm_state64;
            when ap_ST_fsm_state64 => 
                ap_NS_fsm <= ap_ST_fsm_state65;
            when ap_ST_fsm_state65 => 
                ap_NS_fsm <= ap_ST_fsm_state66;
            when ap_ST_fsm_state66 => 
                ap_NS_fsm <= ap_ST_fsm_state67;
            when ap_ST_fsm_state67 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state68 => 
                if (((icmp_ln103_fu_587_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state68))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state69;
                end if;
            when ap_ST_fsm_state69 => 
                if (((icmp_ln104_fu_633_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state69))) then
                    ap_NS_fsm <= ap_ST_fsm_state68;
                else
                    ap_NS_fsm <= ap_ST_fsm_state70;
                end if;
            when ap_ST_fsm_state70 => 
                if (((icmp_ln106_fu_649_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state70))) then
                    ap_NS_fsm <= ap_ST_fsm_state77;
                else
                    ap_NS_fsm <= ap_ST_fsm_state71;
                end if;
            when ap_ST_fsm_state71 => 
                ap_NS_fsm <= ap_ST_fsm_state72;
            when ap_ST_fsm_state72 => 
                ap_NS_fsm <= ap_ST_fsm_state73;
            when ap_ST_fsm_state73 => 
                ap_NS_fsm <= ap_ST_fsm_state74;
            when ap_ST_fsm_state74 => 
                ap_NS_fsm <= ap_ST_fsm_state75;
            when ap_ST_fsm_state75 => 
                ap_NS_fsm <= ap_ST_fsm_state76;
            when ap_ST_fsm_state76 => 
                ap_NS_fsm <= ap_ST_fsm_state70;
            when ap_ST_fsm_state77 => 
                ap_NS_fsm <= ap_ST_fsm_state78;
            when ap_ST_fsm_state78 => 
                ap_NS_fsm <= ap_ST_fsm_state79;
            when ap_ST_fsm_state79 => 
                ap_NS_fsm <= ap_ST_fsm_state80;
            when ap_ST_fsm_state80 => 
                ap_NS_fsm <= ap_ST_fsm_state81;
            when ap_ST_fsm_state81 => 
                ap_NS_fsm <= ap_ST_fsm_state82;
            when ap_ST_fsm_state82 => 
                ap_NS_fsm <= ap_ST_fsm_state83;
            when ap_ST_fsm_state83 => 
                ap_NS_fsm <= ap_ST_fsm_state69;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    BN1_gamma0_address0 <= zext_ln95_fu_556_p1(5 - 1 downto 0);

    BN1_gamma0_ce0_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            BN1_gamma0_ce0 <= ap_const_logic_1;
        else 
            BN1_gamma0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    BN1_var0_address0 <= zext_ln95_fu_556_p1(5 - 1 downto 0);

    BN1_var0_ce0_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            BN1_var0_ce0 <= ap_const_logic_1;
        else 
            BN1_var0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ConvW0_address0 <= zext_ln85_2_fu_501_p1(13 - 1 downto 0);

    ConvW0_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ConvW0_ce0 <= ap_const_logic_1;
        else 
            ConvW0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    U_address0 <= zext_ln107_fu_719_p1(9 - 1 downto 0);

    U_ce0_assign_proc : process(ap_CS_fsm_state83)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state83)) then 
            U_ce0 <= ap_const_logic_1;
        else 
            U_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    U_d0 <= tmp_88_reg_925;

    U_we0_assign_proc : process(ap_CS_fsm_state83)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state83)) then 
            U_we0 <= ap_const_logic_1;
        else 
            U_we0 <= ap_const_logic_0;
        end if; 
    end process;

    X_slice_address0 <= zext_ln85_1_fu_477_p1(11 - 1 downto 0);

    X_slice_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            X_slice_ce0 <= ap_const_logic_1;
        else 
            X_slice_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Y_address0_assign_proc : process(ap_CS_fsm_state4, Y_addr_reg_841, ap_CS_fsm_state35, ap_CS_fsm_state70, ap_CS_fsm_state67, zext_ln88_fu_451_p1, zext_ln95_2_fu_571_p1, zext_ln106_fu_701_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state70)) then 
            Y_address0 <= zext_ln106_fu_701_p1(15 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state67)) then 
            Y_address0 <= Y_addr_reg_841;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state35)) then 
            Y_address0 <= zext_ln95_2_fu_571_p1(15 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Y_address0 <= zext_ln88_fu_451_p1(15 - 1 downto 0);
        else 
            Y_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    Y_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state35, ap_CS_fsm_state70, ap_CS_fsm_state67)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state67) or (ap_const_logic_1 = ap_CS_fsm_state70) or (ap_const_logic_1 = ap_CS_fsm_state35) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            Y_ce0 <= ap_const_logic_1;
        else 
            Y_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Y_d0_assign_proc : process(ap_CS_fsm_state4, select_ln46_reg_861, acc_0_reg_197, ap_CS_fsm_state67)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state67)) then 
            Y_d0 <= select_ln46_reg_861;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Y_d0 <= acc_0_reg_197;
        else 
            Y_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    Y_we0_assign_proc : process(ap_CS_fsm_state4, icmp_ln81_fu_417_p2, ap_CS_fsm_state67)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state67) or ((icmp_ln81_fu_417_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            Y_we0 <= ap_const_logic_1;
        else 
            Y_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln106_1_fu_691_p2 <= std_logic_vector(unsigned(shl_ln106_1_fu_666_p3) + unsigned(sext_ln106_fu_687_p1));
    add_ln106_2_fu_682_p2 <= std_logic_vector(unsigned(c_1_cast_reg_894) + unsigned(shl_ln106_2_fu_674_p3));
    add_ln106_fu_661_p2 <= std_logic_vector(unsigned(p_0_cast_fu_645_p1) + unsigned(sub_ln106_reg_879));
    add_ln107_1_fu_706_p2 <= std_logic_vector(unsigned(zext_ln106_1_reg_874) + unsigned(c_1_cast4_reg_889));
    add_ln107_fu_714_p2 <= std_logic_vector(unsigned(zext_ln107_1_fu_710_p1) + unsigned(shl_ln6_reg_884));
    add_ln82_fu_433_p2 <= std_logic_vector(unsigned(t_0_reg_174) + unsigned(zext_ln82_fu_429_p1));
    add_ln85_1_fu_496_p2 <= std_logic_vector(unsigned(zext_ln81_reg_749) + unsigned(tmp_fu_486_p4));
    add_ln85_fu_472_p2 <= std_logic_vector(unsigned(zext_ln85_fu_468_p1) + unsigned(shl_ln7_reg_762));
    add_ln88_fu_447_p2 <= std_logic_vector(unsigned(shl_ln_reg_731) + unsigned(zext_ln78_reg_736));
    add_ln93_fu_538_p2 <= std_logic_vector(unsigned(zext_ln93_fu_534_p1) + unsigned(shl_ln4_fu_518_p3));
    add_ln95_fu_566_p2 <= std_logic_vector(unsigned(add_ln93_reg_803) + unsigned(zext_ln95_1_fu_562_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state35 <= ap_CS_fsm(34);
    ap_CS_fsm_state36 <= ap_CS_fsm(35);
    ap_CS_fsm_state37 <= ap_CS_fsm(36);
    ap_CS_fsm_state38 <= ap_CS_fsm(37);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state53 <= ap_CS_fsm(52);
    ap_CS_fsm_state54 <= ap_CS_fsm(53);
    ap_CS_fsm_state55 <= ap_CS_fsm(54);
    ap_CS_fsm_state56 <= ap_CS_fsm(55);
    ap_CS_fsm_state59 <= ap_CS_fsm(58);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state60 <= ap_CS_fsm(59);
    ap_CS_fsm_state64 <= ap_CS_fsm(63);
    ap_CS_fsm_state65 <= ap_CS_fsm(64);
    ap_CS_fsm_state66 <= ap_CS_fsm(65);
    ap_CS_fsm_state67 <= ap_CS_fsm(66);
    ap_CS_fsm_state68 <= ap_CS_fsm(67);
    ap_CS_fsm_state69 <= ap_CS_fsm(68);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state70 <= ap_CS_fsm(69);
    ap_CS_fsm_state71 <= ap_CS_fsm(70);
    ap_CS_fsm_state72 <= ap_CS_fsm(71);
    ap_CS_fsm_state76 <= ap_CS_fsm(75);
    ap_CS_fsm_state82 <= ap_CS_fsm(81);
    ap_CS_fsm_state83 <= ap_CS_fsm(82);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state68, icmp_ln103_fu_587_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln103_fu_587_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state68)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state68, icmp_ln103_fu_587_p2)
    begin
        if (((icmp_ln103_fu_587_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state68))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    c_1_cast4_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_reg_278),7));
    c_1_cast_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_reg_278),9));
    c_6_fu_639_p2 <= std_logic_vector(unsigned(c_1_reg_278) + unsigned(ap_const_lv6_1));
    c_fu_550_p2 <= std_logic_vector(unsigned(c_0_reg_256) + unsigned(ap_const_lv6_1));
    e_fu_462_p2 <= std_logic_vector(unsigned(e_0_reg_234) + unsigned(ap_const_lv6_1));
    f_fu_407_p2 <= std_logic_vector(unsigned(f_0_reg_186) + unsigned(ap_const_lv6_1));

    grp_fu_324_p0_assign_proc : process(Y_q0, reg_357, ap_CS_fsm_state36, ap_CS_fsm_state24)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state36)) then 
            grp_fu_324_p0 <= Y_q0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            grp_fu_324_p0 <= reg_357;
        else 
            grp_fu_324_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_328_p0_assign_proc : process(reg_351, BN1_var0_load_reg_831, acc_1_reg_222, acc_2_reg_289, ap_CS_fsm_state11, ap_CS_fsm_state19, ap_CS_fsm_state60, ap_CS_fsm_state72)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state72)) then 
            grp_fu_328_p0 <= acc_2_reg_289;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state60)) then 
            grp_fu_328_p0 <= reg_351;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_328_p0 <= BN1_var0_load_reg_831;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_328_p0 <= acc_1_reg_222;
        else 
            grp_fu_328_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_328_p1_assign_proc : process(reg_351, reg_371, ap_CS_fsm_state11, ap_CS_fsm_state19, ap_CS_fsm_state60, ap_CS_fsm_state72)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state72)) then 
            grp_fu_328_p1 <= reg_371;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state60)) then 
            grp_fu_328_p1 <= ap_const_lv16_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_328_p1 <= ap_const_lv16_1419;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_328_p1 <= reg_351;
        else 
            grp_fu_328_p1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_336_p0_assign_proc : process(X_slice_load_reg_785, BN1_gamma0_load_reg_836, ap_CS_fsm_state7, ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            grp_fu_336_p0 <= BN1_gamma0_load_reg_836;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_336_p0 <= X_slice_load_reg_785;
        else 
            grp_fu_336_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_336_p1_assign_proc : process(ConvW0_load_reg_790, nrm_reg_856, ap_CS_fsm_state7, ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            grp_fu_336_p1 <= nrm_reg_856;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_336_p1 <= ConvW0_load_reg_790;
        else 
            grp_fu_336_p1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln103_fu_587_p2 <= "1" when (u_0_reg_267 = ap_const_lv4_E) else "0";
    icmp_ln104_fu_633_p2 <= "1" when (c_1_reg_278 = ap_const_lv6_24) else "0";
    icmp_ln106_fu_649_p2 <= "1" when (p_0_reg_301 = ap_const_lv2_3) else "0";
    icmp_ln77_fu_377_p2 <= "1" when (t_0_reg_174 = ap_const_lv6_24) else "0";
    icmp_ln78_fu_401_p2 <= "1" when (f_0_reg_186 = ap_const_lv6_20) else "0";
    icmp_ln81_fu_417_p2 <= "1" when (k_0_reg_210 = ap_const_lv3_7) else "0";
    icmp_ln84_fu_456_p2 <= "1" when (e_0_reg_234 = ap_const_lv6_20) else "0";
    icmp_ln92_fu_506_p2 <= "1" when (t_1_reg_245 = ap_const_lv6_2A) else "0";
    icmp_ln94_fu_544_p2 <= "1" when (c_0_reg_256 = ap_const_lv6_24) else "0";
    k_fu_423_p2 <= std_logic_vector(unsigned(k_0_reg_210) + unsigned(ap_const_lv3_1));
    p_0_cast_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_reg_301),7));
    p_fu_655_p2 <= std_logic_vector(unsigned(p_0_reg_301) + unsigned(ap_const_lv2_1));
    select_ln46_fu_575_p3 <= 
        reg_357 when (grp_fu_346_p2(0) = '1') else 
        ap_const_lv16_0;
        sext_ln106_1_fu_697_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln106_1_fu_691_p2),32));

        sext_ln106_fu_687_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln106_2_fu_682_p2),12));

    shl_ln106_1_fu_666_p3 <= (add_ln106_fu_661_p2 & ap_const_lv5_0);
    shl_ln106_2_fu_674_p3 <= (add_ln106_fu_661_p2 & ap_const_lv2_0);
    shl_ln4_fu_518_p3 <= (t_1_reg_245 & ap_const_lv5_0);
    shl_ln5_fu_599_p3 <= (u_0_reg_267 & ap_const_lv2_0);
    shl_ln6_fu_617_p3 <= (u_0_reg_267 & ap_const_lv5_0);
    shl_ln7_fu_439_p3 <= (add_ln82_fu_433_p2 & ap_const_lv5_0);
    shl_ln93_1_fu_526_p3 <= (t_1_reg_245 & ap_const_lv2_0);
    shl_ln_fu_389_p3 <= (t_0_reg_174 & ap_const_lv5_0);
    sub_ln106_fu_611_p2 <= std_logic_vector(unsigned(zext_ln106_1_fu_607_p1) - unsigned(u_0_cast5_fu_583_p1));
    t_2_fu_512_p2 <= std_logic_vector(unsigned(t_1_reg_245) + unsigned(ap_const_lv6_1));
    t_fu_383_p2 <= std_logic_vector(unsigned(t_0_reg_174) + unsigned(ap_const_lv6_1));
    tmp_fu_486_p4 <= ((k_0_reg_210 & trunc_ln85_fu_482_p1) & ap_const_lv5_0);
    trunc_ln85_fu_482_p1 <= e_0_reg_234(5 - 1 downto 0);
    u_0_cast5_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(u_0_reg_267),7));
    u_fu_593_p2 <= std_logic_vector(unsigned(u_0_reg_267) + unsigned(ap_const_lv4_1));
    zext_ln106_1_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln5_fu_599_p3),7));
    zext_ln106_fu_701_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln106_1_fu_697_p1),64));
    zext_ln107_1_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln107_1_fu_706_p2),9));
    zext_ln107_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln107_reg_920),64));
    zext_ln78_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(f_0_reg_186),11));
    zext_ln81_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(f_0_reg_186),13));
    zext_ln82_fu_429_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_210),6));
    zext_ln85_1_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln85_fu_472_p2),64));
    zext_ln85_2_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln85_1_fu_496_p2),64));
    zext_ln85_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_0_reg_234),11));
    zext_ln88_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln88_fu_447_p2),64));
    zext_ln93_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln93_1_fu_526_p3),11));
    zext_ln95_1_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_0_reg_256),11));
    zext_ln95_2_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln95_reg_816),64));
    zext_ln95_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_0_reg_256),64));
end behav;
