-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_bn_act_pool_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Y_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    Y_ce0 : OUT STD_LOGIC;
    Y_we0 : OUT STD_LOGIC;
    Y_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    Y_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    U_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    U_ce0 : OUT STD_LOGIC;
    U_we0 : OUT STD_LOGIC;
    U_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv_bn_act_pool_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000001000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000010000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state57 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000100000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state58 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000001000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state59 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000010000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state60 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000100000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state61 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000001000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state62 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000010000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state63 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000100000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state64 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000001000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state65 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000010000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state66 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000100000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state67 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000001000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state68 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000010000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state69 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000100000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state70 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000001000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state71 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000010000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state72 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000100000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state73 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000001000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state74 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000010000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state75 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000100000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state76 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000001000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state77 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000010000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state78 : STD_LOGIC_VECTOR (87 downto 0) := "0000000000100000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state79 : STD_LOGIC_VECTOR (87 downto 0) := "0000000001000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state80 : STD_LOGIC_VECTOR (87 downto 0) := "0000000010000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state81 : STD_LOGIC_VECTOR (87 downto 0) := "0000000100000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state82 : STD_LOGIC_VECTOR (87 downto 0) := "0000001000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state83 : STD_LOGIC_VECTOR (87 downto 0) := "0000010000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state84 : STD_LOGIC_VECTOR (87 downto 0) := "0000100000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state85 : STD_LOGIC_VECTOR (87 downto 0) := "0001000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state86 : STD_LOGIC_VECTOR (87 downto 0) := "0010000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state87 : STD_LOGIC_VECTOR (87 downto 0) := "0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state88 : STD_LOGIC_VECTOR (87 downto 0) := "1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_56 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3A83126F : STD_LOGIC_VECTOR (31 downto 0) := "00111010100000110001001001101111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_40400000 : STD_LOGIC_VECTOR (31 downto 0) := "01000000010000000000000000000000";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv6_24 : STD_LOGIC_VECTOR (5 downto 0) := "100100";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (87 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal X_slice_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal X_slice_ce0 : STD_LOGIC;
    signal X_slice_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ConvW0_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal ConvW0_ce0 : STD_LOGIC;
    signal ConvW0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal BN1_var0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal BN1_var0_ce0 : STD_LOGIC;
    signal BN1_var0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal BN1_gamma0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal BN1_gamma0_ce0 : STD_LOGIC;
    signal BN1_gamma0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_330_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_350 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state55 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state55 : signal is "none";
    signal grp_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_356 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal ap_CS_fsm_state60 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state60 : signal is "none";
    signal ap_CS_fsm_state72 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state72 : signal is "none";
    signal reg_364 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state35 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state35 : signal is "none";
    signal ap_CS_fsm_state67 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state67 : signal is "none";
    signal grp_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_370 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state51 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state51 : signal is "none";
    signal ap_CS_fsm_state87 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state87 : signal is "none";
    signal t_fu_382_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_reg_767 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal shl_ln_fu_388_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_reg_772 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln70_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln71_fu_396_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln71_reg_777 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal f_fu_406_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal f_reg_785 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln73_fu_412_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln73_reg_790 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln71_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_fu_422_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_reg_798 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal shl_ln7_fu_438_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln7_reg_803 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln73_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_fu_461_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_reg_811 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln76_fu_455_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal X_slice_load_reg_826 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ConvW0_load_reg_831 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_2_fu_511_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_2_reg_839 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal add_ln83_fu_537_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln83_reg_844 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln82_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_fu_549_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_reg_852 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal add_ln85_fu_565_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln85_reg_857 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln84_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal BN1_var0_load_reg_872 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal BN1_gamma0_load_reg_877 : STD_LOGIC_VECTOR (31 downto 0);
    signal Y_addr_reg_882 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state34 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state34 : signal is "none";
    signal grp_fu_345_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_43_reg_887 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_892 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state62 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state62 : signal is "none";
    signal u_fu_634_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal u_reg_900 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state64 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state64 : signal is "none";
    signal zext_ln104_1_fu_648_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln104_1_reg_905 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln101_fu_628_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln104_fu_652_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln104_reg_910 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln6_fu_658_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln6_reg_915 : STD_LOGIC_VECTOR (8 downto 0);
    signal c_1_cast4_fu_666_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal c_1_cast4_reg_920 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state65 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state65 : signal is "none";
    signal c_1_cast_fu_670_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal c_1_cast_reg_925 : STD_LOGIC_VECTOR (8 downto 0);
    signal c_6_fu_680_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_6_reg_933 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_fu_696_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_reg_941 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state66 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state66 : signal is "none";
    signal icmp_ln104_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln105_fu_755_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln105_reg_951 : STD_LOGIC_VECTOR (8 downto 0);
    signal t_0_reg_184 : STD_LOGIC_VECTOR (5 downto 0);
    signal f_0_reg_196 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_0_reg_207 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_0_reg_220 : STD_LOGIC_VECTOR (2 downto 0);
    signal acc_1_reg_232 : STD_LOGIC_VECTOR (31 downto 0);
    signal e_0_reg_244 : STD_LOGIC_VECTOR (5 downto 0);
    signal t_1_reg_255 : STD_LOGIC_VECTOR (5 downto 0);
    signal c_0_reg_266 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state63 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state63 : signal is "none";
    signal u_0_reg_277 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln102_fu_674_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_1_reg_288 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state88 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state88 : signal is "none";
    signal acc1_0_reg_299 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_reg_311 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln78_fu_450_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_1_fu_476_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln76_2_fu_500_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_fu_555_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln85_2_fu_570_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln104_fu_742_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln105_fu_760_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln43_fu_615_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_322_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_322_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state56 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state56 : signal is "none";
    signal ap_CS_fsm_state68 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state68 : signal is "none";
    signal grp_fu_330_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_330_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state52 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state52 : signal is "none";
    signal grp_fu_334_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_334_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state36 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state36 : signal is "none";
    signal ap_CS_fsm_state61 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state61 : signal is "none";
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal zext_ln74_fu_428_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln74_fu_432_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln78_fu_446_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln76_fu_467_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln76_fu_471_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln76_fu_481_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_485_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln76_1_fu_495_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln83_1_fu_525_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln83_fu_533_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln4_fu_517_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln85_1_fu_561_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal bitcast_ln43_fu_574_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_578_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln43_fu_588_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln43_4_fu_598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln43_fu_592_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln43_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln43_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln5_fu_640_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal u_0_cast5_fu_624_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_0_cast_fu_686_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln104_fu_702_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln104_2_fu_715_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln104_2_fu_723_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln104_1_fu_707_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln104_fu_728_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln104_1_fu_732_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln104_1_fu_738_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln105_1_fu_747_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln105_1_fu_751_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (87 downto 0);

    component main_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_fdiv_32ns_32ns_32_16_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_fcmp_32ns_32ns_1_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component main_fsqrt_32ns_32ns_32_12_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv_bn_act_pool_4_X_slice IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv_bn_act_pool_4_ConvW0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv_bn_act_pool_4_BN1_var0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    X_slice_U : component conv_bn_act_pool_4_X_slice
    generic map (
        DataWidth => 32,
        AddressRange => 1344,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => X_slice_address0,
        ce0 => X_slice_ce0,
        q0 => X_slice_q0);

    ConvW0_U : component conv_bn_act_pool_4_ConvW0
    generic map (
        DataWidth => 32,
        AddressRange => 7168,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ConvW0_address0,
        ce0 => ConvW0_ce0,
        q0 => ConvW0_q0);

    BN1_var0_U : component conv_bn_act_pool_4_BN1_var0
    generic map (
        DataWidth => 32,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => BN1_var0_address0,
        ce0 => BN1_var0_ce0,
        q0 => BN1_var0_q0);

    BN1_gamma0_U : component conv_bn_act_pool_4_BN1_var0
    generic map (
        DataWidth => 32,
        AddressRange => 32,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => BN1_gamma0_address0,
        ce0 => BN1_gamma0_ce0,
        q0 => BN1_gamma0_q0);

    main_fadd_32ns_32ns_32_5_full_dsp_1_U1 : component main_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_322_p0,
        din1 => grp_fu_322_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_322_p2);

    main_fmul_32ns_32ns_32_4_max_dsp_1_U2 : component main_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_330_p0,
        din1 => grp_fu_330_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_330_p2);

    main_fdiv_32ns_32ns_32_16_1_U3 : component main_fdiv_32ns_32ns_32_16_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_334_p0,
        din1 => grp_fu_334_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_334_p2);

    main_fcmp_32ns_32ns_1_2_1_U4 : component main_fcmp_32ns_32ns_1_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_356,
        din1 => ap_const_lv32_0,
        ce => ap_const_logic_1,
        opcode => ap_const_lv5_2,
        dout => grp_fu_340_p2);

    main_fsqrt_32ns_32ns_32_12_1_U5 : component main_fsqrt_32ns_32ns_32_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_0,
        din1 => reg_356,
        ce => ap_const_logic_1,
        dout => grp_fu_345_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    acc1_0_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln102_fu_674_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state65))) then 
                acc1_0_reg_299 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state72)) then 
                acc1_0_reg_299 <= grp_fu_322_p2;
            end if; 
        end if;
    end process;

    acc_0_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln76_fu_455_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                acc_0_reg_207 <= acc_1_reg_232;
            elsif (((icmp_ln71_fu_400_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                acc_0_reg_207 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    acc_1_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                acc_1_reg_232 <= grp_fu_322_p2;
            elsif (((icmp_ln73_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                acc_1_reg_232 <= acc_0_reg_207;
            end if; 
        end if;
    end process;

    c_0_reg_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state63)) then 
                c_0_reg_266 <= c_reg_852;
            elsif (((icmp_ln82_fu_505_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                c_0_reg_266 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    c_1_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln101_fu_628_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state64))) then 
                c_1_reg_288 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state88)) then 
                c_1_reg_288 <= c_6_reg_933;
            end if; 
        end if;
    end process;

    e_0_reg_244_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                e_0_reg_244 <= e_reg_811;
            elsif (((icmp_ln73_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                e_0_reg_244 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    f_0_reg_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln70_fu_376_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                f_0_reg_196 <= ap_const_lv6_0;
            elsif (((icmp_ln73_fu_416_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                f_0_reg_196 <= f_reg_785;
            end if; 
        end if;
    end process;

    k_0_reg_220_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln76_fu_455_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                k_0_reg_220 <= k_reg_798;
            elsif (((icmp_ln71_fu_400_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                k_0_reg_220 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    p_0_reg_311_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln102_fu_674_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state65))) then 
                p_0_reg_311 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state72)) then 
                p_0_reg_311 <= p_reg_941;
            end if; 
        end if;
    end process;

    t_0_reg_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_fu_400_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                t_0_reg_184 <= t_reg_767;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_0_reg_184 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    t_1_reg_255_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln70_fu_376_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_1_reg_255 <= ap_const_lv6_0;
            elsif (((icmp_ln84_fu_543_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                t_1_reg_255 <= t_2_reg_839;
            end if; 
        end if;
    end process;

    u_0_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln82_fu_505_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                u_0_reg_277 <= ap_const_lv4_0;
            elsif (((icmp_ln102_fu_674_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state65))) then 
                u_0_reg_277 <= u_reg_900;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                BN1_gamma0_load_reg_877 <= BN1_gamma0_q0;
                BN1_var0_load_reg_872 <= BN1_var0_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                ConvW0_load_reg_831 <= ConvW0_q0;
                X_slice_load_reg_826 <= X_slice_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state34)) then
                    Y_addr_reg_882(10 downto 0) <= zext_ln85_2_fu_570_p1(15 - 1 downto 0)(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln104_fu_690_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state66))) then
                add_ln105_reg_951 <= add_ln105_fu_755_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln82_fu_505_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    add_ln83_reg_844(10 downto 2) <= add_ln83_fu_537_p2(10 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln84_fu_543_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                add_ln85_reg_857 <= add_ln85_fu_565_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state65)) then
                    c_1_cast4_reg_920(5 downto 0) <= c_1_cast4_fu_666_p1(5 downto 0);
                    c_1_cast_reg_925(5 downto 0) <= c_1_cast_fu_670_p1(5 downto 0);
                c_6_reg_933 <= c_6_fu_680_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                c_reg_852 <= c_fu_549_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                e_reg_811 <= e_fu_461_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                f_reg_785 <= f_fu_406_p2;
                    zext_ln71_reg_777(5 downto 0) <= zext_ln71_fu_396_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                k_reg_798 <= k_fu_422_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state66)) then
                p_reg_941 <= p_fu_696_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state55) or (ap_const_logic_1 = ap_CS_fsm_state10))) then
                reg_350 <= grp_fu_330_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state72) or (ap_const_logic_1 = ap_CS_fsm_state60) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state15))) then
                reg_356 <= grp_fu_322_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state67) or (ap_const_logic_1 = ap_CS_fsm_state35))) then
                reg_364 <= Y_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state87) or (ap_const_logic_1 = ap_CS_fsm_state51))) then
                reg_370 <= grp_fu_334_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln101_fu_628_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state64))) then
                    shl_ln6_reg_915(8 downto 5) <= shl_ln6_fu_658_p3(8 downto 5);
                sub_ln104_reg_910 <= sub_ln104_fu_652_p2;
                    zext_ln104_1_reg_905(5 downto 2) <= zext_ln104_1_fu_648_p1(5 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln73_fu_416_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    shl_ln7_reg_803(10 downto 5) <= shl_ln7_fu_438_p3(10 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln70_fu_376_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    shl_ln_reg_772(10 downto 5) <= shl_ln_fu_388_p3(10 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                t_2_reg_839 <= t_2_fu_511_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                t_reg_767 <= t_fu_382_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state35)) then
                tmp_43_reg_887 <= grp_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state62)) then
                tmp_9_reg_892 <= grp_fu_340_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state64)) then
                u_reg_900 <= u_fu_634_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln71_fu_400_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    zext_ln73_reg_790(5 downto 0) <= zext_ln73_fu_412_p1(5 downto 0);
            end if;
        end if;
    end process;
    shl_ln_reg_772(4 downto 0) <= "00000";
    zext_ln71_reg_777(10 downto 6) <= "00000";
    zext_ln73_reg_790(12 downto 6) <= "0000000";
    shl_ln7_reg_803(4 downto 0) <= "00000";
    add_ln83_reg_844(1 downto 0) <= "00";
    Y_addr_reg_882(14 downto 11) <= "0000";
    zext_ln104_1_reg_905(1 downto 0) <= "00";
    zext_ln104_1_reg_905(6) <= '0';
    shl_ln6_reg_915(4 downto 0) <= "00000";
    c_1_cast4_reg_920(6) <= '0';
    c_1_cast_reg_925(8 downto 6) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln70_fu_376_p2, ap_CS_fsm_state3, icmp_ln71_fu_400_p2, ap_CS_fsm_state4, icmp_ln73_fu_416_p2, ap_CS_fsm_state5, icmp_ln76_fu_455_p2, ap_CS_fsm_state16, icmp_ln82_fu_505_p2, ap_CS_fsm_state17, icmp_ln84_fu_543_p2, ap_CS_fsm_state64, icmp_ln101_fu_628_p2, ap_CS_fsm_state65, ap_CS_fsm_state66, icmp_ln104_fu_690_p2, icmp_ln102_fu_674_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln70_fu_376_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln71_fu_400_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln73_fu_416_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln76_fu_455_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state16 => 
                if (((icmp_ln82_fu_505_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state64;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state17 => 
                if (((icmp_ln84_fu_543_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state50;
            when ap_ST_fsm_state50 => 
                ap_NS_fsm <= ap_ST_fsm_state51;
            when ap_ST_fsm_state51 => 
                ap_NS_fsm <= ap_ST_fsm_state52;
            when ap_ST_fsm_state52 => 
                ap_NS_fsm <= ap_ST_fsm_state53;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                ap_NS_fsm <= ap_ST_fsm_state55;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state57;
            when ap_ST_fsm_state57 => 
                ap_NS_fsm <= ap_ST_fsm_state58;
            when ap_ST_fsm_state58 => 
                ap_NS_fsm <= ap_ST_fsm_state59;
            when ap_ST_fsm_state59 => 
                ap_NS_fsm <= ap_ST_fsm_state60;
            when ap_ST_fsm_state60 => 
                ap_NS_fsm <= ap_ST_fsm_state61;
            when ap_ST_fsm_state61 => 
                ap_NS_fsm <= ap_ST_fsm_state62;
            when ap_ST_fsm_state62 => 
                ap_NS_fsm <= ap_ST_fsm_state63;
            when ap_ST_fsm_state63 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state64 => 
                if (((icmp_ln101_fu_628_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state64))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state65;
                end if;
            when ap_ST_fsm_state65 => 
                if (((icmp_ln102_fu_674_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state65))) then
                    ap_NS_fsm <= ap_ST_fsm_state64;
                else
                    ap_NS_fsm <= ap_ST_fsm_state66;
                end if;
            when ap_ST_fsm_state66 => 
                if (((icmp_ln104_fu_690_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state66))) then
                    ap_NS_fsm <= ap_ST_fsm_state73;
                else
                    ap_NS_fsm <= ap_ST_fsm_state67;
                end if;
            when ap_ST_fsm_state67 => 
                ap_NS_fsm <= ap_ST_fsm_state68;
            when ap_ST_fsm_state68 => 
                ap_NS_fsm <= ap_ST_fsm_state69;
            when ap_ST_fsm_state69 => 
                ap_NS_fsm <= ap_ST_fsm_state70;
            when ap_ST_fsm_state70 => 
                ap_NS_fsm <= ap_ST_fsm_state71;
            when ap_ST_fsm_state71 => 
                ap_NS_fsm <= ap_ST_fsm_state72;
            when ap_ST_fsm_state72 => 
                ap_NS_fsm <= ap_ST_fsm_state66;
            when ap_ST_fsm_state73 => 
                ap_NS_fsm <= ap_ST_fsm_state74;
            when ap_ST_fsm_state74 => 
                ap_NS_fsm <= ap_ST_fsm_state75;
            when ap_ST_fsm_state75 => 
                ap_NS_fsm <= ap_ST_fsm_state76;
            when ap_ST_fsm_state76 => 
                ap_NS_fsm <= ap_ST_fsm_state77;
            when ap_ST_fsm_state77 => 
                ap_NS_fsm <= ap_ST_fsm_state78;
            when ap_ST_fsm_state78 => 
                ap_NS_fsm <= ap_ST_fsm_state79;
            when ap_ST_fsm_state79 => 
                ap_NS_fsm <= ap_ST_fsm_state80;
            when ap_ST_fsm_state80 => 
                ap_NS_fsm <= ap_ST_fsm_state81;
            when ap_ST_fsm_state81 => 
                ap_NS_fsm <= ap_ST_fsm_state82;
            when ap_ST_fsm_state82 => 
                ap_NS_fsm <= ap_ST_fsm_state83;
            when ap_ST_fsm_state83 => 
                ap_NS_fsm <= ap_ST_fsm_state84;
            when ap_ST_fsm_state84 => 
                ap_NS_fsm <= ap_ST_fsm_state85;
            when ap_ST_fsm_state85 => 
                ap_NS_fsm <= ap_ST_fsm_state86;
            when ap_ST_fsm_state86 => 
                ap_NS_fsm <= ap_ST_fsm_state87;
            when ap_ST_fsm_state87 => 
                ap_NS_fsm <= ap_ST_fsm_state88;
            when ap_ST_fsm_state88 => 
                ap_NS_fsm <= ap_ST_fsm_state65;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    BN1_gamma0_address0 <= zext_ln85_fu_555_p1(5 - 1 downto 0);

    BN1_gamma0_ce0_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            BN1_gamma0_ce0 <= ap_const_logic_1;
        else 
            BN1_gamma0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    BN1_var0_address0 <= zext_ln85_fu_555_p1(5 - 1 downto 0);

    BN1_var0_ce0_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            BN1_var0_ce0 <= ap_const_logic_1;
        else 
            BN1_var0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ConvW0_address0 <= zext_ln76_2_fu_500_p1(13 - 1 downto 0);

    ConvW0_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ConvW0_ce0 <= ap_const_logic_1;
        else 
            ConvW0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    U_address0 <= zext_ln105_fu_760_p1(9 - 1 downto 0);

    U_ce0_assign_proc : process(ap_CS_fsm_state88)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state88)) then 
            U_ce0 <= ap_const_logic_1;
        else 
            U_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    U_d0 <= reg_370;

    U_we0_assign_proc : process(ap_CS_fsm_state88)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state88)) then 
            U_we0 <= ap_const_logic_1;
        else 
            U_we0 <= ap_const_logic_0;
        end if; 
    end process;

    X_slice_address0 <= zext_ln76_1_fu_476_p1(11 - 1 downto 0);

    X_slice_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            X_slice_ce0 <= ap_const_logic_1;
        else 
            X_slice_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Y_address0_assign_proc : process(ap_CS_fsm_state4, Y_addr_reg_882, ap_CS_fsm_state34, ap_CS_fsm_state66, ap_CS_fsm_state63, zext_ln78_fu_450_p1, zext_ln85_2_fu_570_p1, zext_ln104_fu_742_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state66)) then 
            Y_address0 <= zext_ln104_fu_742_p1(15 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state63)) then 
            Y_address0 <= Y_addr_reg_882;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state34)) then 
            Y_address0 <= zext_ln85_2_fu_570_p1(15 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Y_address0 <= zext_ln78_fu_450_p1(15 - 1 downto 0);
        else 
            Y_address0 <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;


    Y_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state34, ap_CS_fsm_state66, ap_CS_fsm_state63)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state63) or (ap_const_logic_1 = ap_CS_fsm_state66) or (ap_const_logic_1 = ap_CS_fsm_state34) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            Y_ce0 <= ap_const_logic_1;
        else 
            Y_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Y_d0_assign_proc : process(ap_CS_fsm_state4, acc_0_reg_207, ap_CS_fsm_state63, select_ln43_fu_615_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state63)) then 
            Y_d0 <= select_ln43_fu_615_p3;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Y_d0 <= acc_0_reg_207;
        else 
            Y_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    Y_we0_assign_proc : process(ap_CS_fsm_state4, icmp_ln73_fu_416_p2, ap_CS_fsm_state63)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state63) or ((icmp_ln73_fu_416_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            Y_we0 <= ap_const_logic_1;
        else 
            Y_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln104_1_fu_732_p2 <= std_logic_vector(unsigned(shl_ln104_1_fu_707_p3) + unsigned(sext_ln104_fu_728_p1));
    add_ln104_2_fu_723_p2 <= std_logic_vector(unsigned(c_1_cast_reg_925) + unsigned(shl_ln104_2_fu_715_p3));
    add_ln104_fu_702_p2 <= std_logic_vector(unsigned(p_0_cast_fu_686_p1) + unsigned(sub_ln104_reg_910));
    add_ln105_1_fu_747_p2 <= std_logic_vector(unsigned(zext_ln104_1_reg_905) + unsigned(c_1_cast4_reg_920));
    add_ln105_fu_755_p2 <= std_logic_vector(unsigned(zext_ln105_1_fu_751_p1) + unsigned(shl_ln6_reg_915));
    add_ln74_fu_432_p2 <= std_logic_vector(unsigned(t_0_reg_184) + unsigned(zext_ln74_fu_428_p1));
    add_ln76_1_fu_495_p2 <= std_logic_vector(unsigned(zext_ln73_reg_790) + unsigned(tmp_fu_485_p4));
    add_ln76_fu_471_p2 <= std_logic_vector(unsigned(zext_ln76_fu_467_p1) + unsigned(shl_ln7_reg_803));
    add_ln78_fu_446_p2 <= std_logic_vector(unsigned(shl_ln_reg_772) + unsigned(zext_ln71_reg_777));
    add_ln83_fu_537_p2 <= std_logic_vector(unsigned(zext_ln83_fu_533_p1) + unsigned(shl_ln4_fu_517_p3));
    add_ln85_fu_565_p2 <= std_logic_vector(unsigned(add_ln83_reg_844) + unsigned(zext_ln85_1_fu_561_p1));
    and_ln43_fu_610_p2 <= (tmp_9_reg_892 and or_ln43_fu_604_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state34 <= ap_CS_fsm(33);
    ap_CS_fsm_state35 <= ap_CS_fsm(34);
    ap_CS_fsm_state36 <= ap_CS_fsm(35);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state51 <= ap_CS_fsm(50);
    ap_CS_fsm_state52 <= ap_CS_fsm(51);
    ap_CS_fsm_state55 <= ap_CS_fsm(54);
    ap_CS_fsm_state56 <= ap_CS_fsm(55);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state60 <= ap_CS_fsm(59);
    ap_CS_fsm_state61 <= ap_CS_fsm(60);
    ap_CS_fsm_state62 <= ap_CS_fsm(61);
    ap_CS_fsm_state63 <= ap_CS_fsm(62);
    ap_CS_fsm_state64 <= ap_CS_fsm(63);
    ap_CS_fsm_state65 <= ap_CS_fsm(64);
    ap_CS_fsm_state66 <= ap_CS_fsm(65);
    ap_CS_fsm_state67 <= ap_CS_fsm(66);
    ap_CS_fsm_state68 <= ap_CS_fsm(67);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state72 <= ap_CS_fsm(71);
    ap_CS_fsm_state87 <= ap_CS_fsm(86);
    ap_CS_fsm_state88 <= ap_CS_fsm(87);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state64, icmp_ln101_fu_628_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((icmp_ln101_fu_628_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state64)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state64, icmp_ln101_fu_628_p2)
    begin
        if (((icmp_ln101_fu_628_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state64))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bitcast_ln43_fu_574_p1 <= reg_356;
    c_1_cast4_fu_666_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_reg_288),7));
    c_1_cast_fu_670_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_reg_288),9));
    c_6_fu_680_p2 <= std_logic_vector(unsigned(c_1_reg_288) + unsigned(ap_const_lv6_1));
    c_fu_549_p2 <= std_logic_vector(unsigned(c_0_reg_266) + unsigned(ap_const_lv6_1));
    e_fu_461_p2 <= std_logic_vector(unsigned(e_0_reg_244) + unsigned(ap_const_lv6_1));
    f_fu_406_p2 <= std_logic_vector(unsigned(f_0_reg_196) + unsigned(ap_const_lv6_1));

    grp_fu_322_p0_assign_proc : process(reg_350, BN1_var0_load_reg_872, acc_1_reg_232, acc1_0_reg_299, ap_CS_fsm_state11, ap_CS_fsm_state19, ap_CS_fsm_state56, ap_CS_fsm_state68)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state68)) then 
            grp_fu_322_p0 <= acc1_0_reg_299;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            grp_fu_322_p0 <= reg_350;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_322_p0 <= BN1_var0_load_reg_872;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_322_p0 <= acc_1_reg_232;
        else 
            grp_fu_322_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_322_p1_assign_proc : process(reg_350, reg_364, ap_CS_fsm_state11, ap_CS_fsm_state19, ap_CS_fsm_state56, ap_CS_fsm_state68)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state68)) then 
            grp_fu_322_p1 <= reg_364;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            grp_fu_322_p1 <= ap_const_lv32_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            grp_fu_322_p1 <= ap_const_lv32_3A83126F;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_322_p1 <= reg_350;
        else 
            grp_fu_322_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_330_p0_assign_proc : process(X_slice_load_reg_826, BN1_gamma0_load_reg_877, ap_CS_fsm_state7, ap_CS_fsm_state52)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state52)) then 
            grp_fu_330_p0 <= BN1_gamma0_load_reg_877;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_330_p0 <= X_slice_load_reg_826;
        else 
            grp_fu_330_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_330_p1_assign_proc : process(reg_370, ConvW0_load_reg_831, ap_CS_fsm_state7, ap_CS_fsm_state52)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state52)) then 
            grp_fu_330_p1 <= reg_370;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_330_p1 <= ConvW0_load_reg_831;
        else 
            grp_fu_330_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_334_p0_assign_proc : process(reg_364, ap_CS_fsm_state66, acc1_0_reg_299, ap_CS_fsm_state36)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state66)) then 
            grp_fu_334_p0 <= acc1_0_reg_299;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state36)) then 
            grp_fu_334_p0 <= reg_364;
        else 
            grp_fu_334_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_334_p1_assign_proc : process(tmp_43_reg_887, ap_CS_fsm_state66, ap_CS_fsm_state36)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state66)) then 
            grp_fu_334_p1 <= ap_const_lv32_40400000;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state36)) then 
            grp_fu_334_p1 <= tmp_43_reg_887;
        else 
            grp_fu_334_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln101_fu_628_p2 <= "1" when (u_0_reg_277 = ap_const_lv4_E) else "0";
    icmp_ln102_fu_674_p2 <= "1" when (c_1_reg_288 = ap_const_lv6_24) else "0";
    icmp_ln104_fu_690_p2 <= "1" when (p_0_reg_311 = ap_const_lv2_3) else "0";
    icmp_ln43_4_fu_598_p2 <= "1" when (trunc_ln43_fu_588_p1 = ap_const_lv23_0) else "0";
    icmp_ln43_fu_592_p2 <= "0" when (tmp_8_fu_578_p4 = ap_const_lv8_FF) else "1";
    icmp_ln70_fu_376_p2 <= "1" when (t_0_reg_184 = ap_const_lv6_24) else "0";
    icmp_ln71_fu_400_p2 <= "1" when (f_0_reg_196 = ap_const_lv6_20) else "0";
    icmp_ln73_fu_416_p2 <= "1" when (k_0_reg_220 = ap_const_lv3_7) else "0";
    icmp_ln76_fu_455_p2 <= "1" when (e_0_reg_244 = ap_const_lv6_20) else "0";
    icmp_ln82_fu_505_p2 <= "1" when (t_1_reg_255 = ap_const_lv6_2A) else "0";
    icmp_ln84_fu_543_p2 <= "1" when (c_0_reg_266 = ap_const_lv6_24) else "0";
    k_fu_422_p2 <= std_logic_vector(unsigned(k_0_reg_220) + unsigned(ap_const_lv3_1));
    or_ln43_fu_604_p2 <= (icmp_ln43_fu_592_p2 or icmp_ln43_4_fu_598_p2);
    p_0_cast_fu_686_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_reg_311),7));
    p_fu_696_p2 <= std_logic_vector(unsigned(p_0_reg_311) + unsigned(ap_const_lv2_1));
    select_ln43_fu_615_p3 <= 
        reg_356 when (and_ln43_fu_610_p2(0) = '1') else 
        ap_const_lv32_0;
        sext_ln104_1_fu_738_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln104_1_fu_732_p2),32));

        sext_ln104_fu_728_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln104_2_fu_723_p2),12));

    shl_ln104_1_fu_707_p3 <= (add_ln104_fu_702_p2 & ap_const_lv5_0);
    shl_ln104_2_fu_715_p3 <= (add_ln104_fu_702_p2 & ap_const_lv2_0);
    shl_ln4_fu_517_p3 <= (t_1_reg_255 & ap_const_lv5_0);
    shl_ln5_fu_640_p3 <= (u_0_reg_277 & ap_const_lv2_0);
    shl_ln6_fu_658_p3 <= (u_0_reg_277 & ap_const_lv5_0);
    shl_ln7_fu_438_p3 <= (add_ln74_fu_432_p2 & ap_const_lv5_0);
    shl_ln83_1_fu_525_p3 <= (t_1_reg_255 & ap_const_lv2_0);
    shl_ln_fu_388_p3 <= (t_0_reg_184 & ap_const_lv5_0);
    sub_ln104_fu_652_p2 <= std_logic_vector(unsigned(zext_ln104_1_fu_648_p1) - unsigned(u_0_cast5_fu_624_p1));
    t_2_fu_511_p2 <= std_logic_vector(unsigned(t_1_reg_255) + unsigned(ap_const_lv6_1));
    t_fu_382_p2 <= std_logic_vector(unsigned(t_0_reg_184) + unsigned(ap_const_lv6_1));
    tmp_8_fu_578_p4 <= bitcast_ln43_fu_574_p1(30 downto 23);
    tmp_fu_485_p4 <= ((k_0_reg_220 & trunc_ln76_fu_481_p1) & ap_const_lv5_0);
    trunc_ln43_fu_588_p1 <= bitcast_ln43_fu_574_p1(23 - 1 downto 0);
    trunc_ln76_fu_481_p1 <= e_0_reg_244(5 - 1 downto 0);
    u_0_cast5_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(u_0_reg_277),7));
    u_fu_634_p2 <= std_logic_vector(unsigned(u_0_reg_277) + unsigned(ap_const_lv4_1));
    zext_ln104_1_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln5_fu_640_p3),7));
    zext_ln104_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln104_1_fu_738_p1),64));
    zext_ln105_1_fu_751_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln105_1_fu_747_p2),9));
    zext_ln105_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln105_reg_951),64));
    zext_ln71_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(f_0_reg_196),11));
    zext_ln73_fu_412_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(f_0_reg_196),13));
    zext_ln74_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_220),6));
    zext_ln76_1_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_fu_471_p2),64));
    zext_ln76_2_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln76_1_fu_495_p2),64));
    zext_ln76_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_0_reg_244),11));
    zext_ln78_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln78_fu_446_p2),64));
    zext_ln83_fu_533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln83_1_fu_525_p3),11));
    zext_ln85_1_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_0_reg_266),11));
    zext_ln85_2_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln85_reg_857),64));
    zext_ln85_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_0_reg_266),64));
end behav;
