-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv1d_valid_dyn_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Y_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    Y_ce0 : OUT STD_LOGIC;
    Y_we0 : OUT STD_LOGIC;
    Y_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv1d_valid_dyn_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (14 downto 0) := "000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (14 downto 0) := "000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (14 downto 0) := "000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (14 downto 0) := "000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (14 downto 0) := "000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (14 downto 0) := "000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (14 downto 0) := "000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (14 downto 0) := "000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (14 downto 0) := "000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (14 downto 0) := "001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (14 downto 0) := "010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv8_90 : STD_LOGIC_VECTOR (7 downto 0) := "10010000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal X04_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal X04_ce0 : STD_LOGIC;
    signal X04_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ConvW2_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal ConvW2_ce0 : STD_LOGIC;
    signal ConvW2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_fu_167_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_reg_289 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal shl_ln_fu_173_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln_reg_294 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln64_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln65_fu_181_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln65_reg_299 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal f_fu_191_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal f_reg_308 : STD_LOGIC_VECTOR (5 downto 0);
    signal k_fu_203_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal k_reg_316 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal shl_ln8_fu_219_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln8_reg_321 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln67_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_fu_242_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal e_reg_329 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln70_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal X04_load_reg_344 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ConvW2_load_reg_349 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_157_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_354 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_fu_152_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal t_0_reg_81 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln65_fu_185_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal f_0_reg_93 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_0_reg_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_0_reg_117 : STD_LOGIC_VECTOR (2 downto 0);
    signal acc_1_reg_129 : STD_LOGIC_VECTOR (31 downto 0);
    signal e_0_reg_141 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln72_fu_231_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_5_fu_257_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln70_6_fu_281_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal zext_ln68_fu_209_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln68_fu_213_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln72_fu_227_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln70_fu_248_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln70_fu_252_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln70_fu_262_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp1_fu_266_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln70_5_fu_276_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (14 downto 0);

    component main_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component main_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv1d_valid_dyn_2_X04 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component conv1d_valid_dyn_2_ConvW2 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    X04_U : component conv1d_valid_dyn_2_X04
    generic map (
        DataWidth => 32,
        AddressRange => 4800,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => X04_address0,
        ce0 => X04_ce0,
        q0 => X04_q0);

    ConvW2_U : component conv1d_valid_dyn_2_ConvW2
    generic map (
        DataWidth => 32,
        AddressRange => 7168,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ConvW2_address0,
        ce0 => ConvW2_ce0,
        q0 => ConvW2_q0);

    main_fadd_32ns_32ns_32_5_full_dsp_1_U75 : component main_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => acc_1_reg_129,
        din1 => tmp_reg_354,
        ce => ap_const_logic_1,
        dout => grp_fu_152_p2);

    main_fmul_32ns_32ns_32_4_max_dsp_1_U76 : component main_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => X04_load_reg_344,
        din1 => ConvW2_load_reg_349,
        ce => ap_const_logic_1,
        dout => grp_fu_157_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    acc_0_reg_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln65_fu_185_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                acc_0_reg_104 <= ap_const_lv32_0;
            elsif (((icmp_ln70_fu_236_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                acc_0_reg_104 <= acc_1_reg_129;
            end if; 
        end if;
    end process;

    acc_1_reg_129_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                acc_1_reg_129 <= grp_fu_152_p2;
            elsif (((icmp_ln67_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                acc_1_reg_129 <= acc_0_reg_104;
            end if; 
        end if;
    end process;

    e_0_reg_141_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                e_0_reg_141 <= e_reg_329;
            elsif (((icmp_ln67_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                e_0_reg_141 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    f_0_reg_93_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln64_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                f_0_reg_93 <= ap_const_lv6_0;
            elsif (((icmp_ln67_fu_197_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                f_0_reg_93 <= f_reg_308;
            end if; 
        end if;
    end process;

    k_0_reg_117_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln65_fu_185_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                k_0_reg_117 <= ap_const_lv3_0;
            elsif (((icmp_ln70_fu_236_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                k_0_reg_117 <= k_reg_316;
            end if; 
        end if;
    end process;

    t_0_reg_81_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln65_fu_185_p2 = ap_const_lv1_1))) then 
                t_0_reg_81 <= t_reg_289;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_0_reg_81 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                ConvW2_load_reg_349 <= ConvW2_q0;
                X04_load_reg_344 <= X04_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                e_reg_329 <= e_fu_242_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                f_reg_308 <= f_fu_191_p2;
                    zext_ln65_reg_299(5 downto 0) <= zext_ln65_fu_181_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                k_reg_316 <= k_fu_203_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln67_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    shl_ln8_reg_321(12 downto 5) <= shl_ln8_fu_219_p3(12 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln64_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    shl_ln_reg_294(12 downto 5) <= shl_ln_fu_173_p3(12 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                t_reg_289 <= t_fu_167_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                tmp_reg_354 <= grp_fu_157_p2;
            end if;
        end if;
    end process;
    shl_ln_reg_294(4 downto 0) <= "00000";
    zext_ln65_reg_299(12 downto 6) <= "0000000";
    shl_ln8_reg_321(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln64_fu_161_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln67_fu_197_p2, ap_CS_fsm_state5, icmp_ln70_fu_236_p2, icmp_ln65_fu_185_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln64_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln65_fu_185_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln67_fu_197_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln70_fu_236_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXX";
        end case;
    end process;
    ConvW2_address0 <= zext_ln70_6_fu_281_p1(13 - 1 downto 0);

    ConvW2_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ConvW2_ce0 <= ap_const_logic_1;
        else 
            ConvW2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    X04_address0 <= zext_ln70_5_fu_257_p1(13 - 1 downto 0);

    X04_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            X04_ce0 <= ap_const_logic_1;
        else 
            X04_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Y_address0 <= zext_ln72_fu_231_p1(13 - 1 downto 0);

    Y_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Y_ce0 <= ap_const_logic_1;
        else 
            Y_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Y_d0 <= acc_0_reg_104;

    Y_we0_assign_proc : process(ap_CS_fsm_state4, icmp_ln67_fu_197_p2)
    begin
        if (((icmp_ln67_fu_197_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            Y_we0 <= ap_const_logic_1;
        else 
            Y_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln68_fu_213_p2 <= std_logic_vector(unsigned(t_0_reg_81) + unsigned(zext_ln68_fu_209_p1));
    add_ln70_5_fu_276_p2 <= std_logic_vector(unsigned(zext_ln65_reg_299) + unsigned(tmp1_fu_266_p4));
    add_ln70_fu_252_p2 <= std_logic_vector(unsigned(zext_ln70_fu_248_p1) + unsigned(shl_ln8_reg_321));
    add_ln72_fu_227_p2 <= std_logic_vector(unsigned(shl_ln_reg_294) + unsigned(zext_ln65_reg_299));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln64_fu_161_p2)
    begin
        if ((((icmp_ln64_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln64_fu_161_p2)
    begin
        if (((icmp_ln64_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    e_fu_242_p2 <= std_logic_vector(unsigned(e_0_reg_141) + unsigned(ap_const_lv6_1));
    f_fu_191_p2 <= std_logic_vector(unsigned(f_0_reg_93) + unsigned(ap_const_lv6_1));
    icmp_ln64_fu_161_p2 <= "1" when (t_0_reg_81 = ap_const_lv8_90) else "0";
    icmp_ln65_fu_185_p2 <= "1" when (f_0_reg_93 = ap_const_lv6_20) else "0";
    icmp_ln67_fu_197_p2 <= "1" when (k_0_reg_117 = ap_const_lv3_7) else "0";
    icmp_ln70_fu_236_p2 <= "1" when (e_0_reg_141 = ap_const_lv6_20) else "0";
    k_fu_203_p2 <= std_logic_vector(unsigned(k_0_reg_117) + unsigned(ap_const_lv3_1));
    shl_ln8_fu_219_p3 <= (add_ln68_fu_213_p2 & ap_const_lv5_0);
    shl_ln_fu_173_p3 <= (t_0_reg_81 & ap_const_lv5_0);
    t_fu_167_p2 <= std_logic_vector(unsigned(t_0_reg_81) + unsigned(ap_const_lv8_1));
    tmp1_fu_266_p4 <= ((k_0_reg_117 & trunc_ln70_fu_262_p1) & ap_const_lv5_0);
    trunc_ln70_fu_262_p1 <= e_0_reg_141(5 - 1 downto 0);
    zext_ln65_fu_181_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(f_0_reg_93),13));
    zext_ln68_fu_209_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_reg_117),8));
    zext_ln70_5_fu_257_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_fu_252_p2),64));
    zext_ln70_6_fu_281_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_5_fu_276_p2),64));
    zext_ln70_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(e_0_reg_141),13));
    zext_ln72_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_fu_227_p2),64));
end behav;
