// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv1d_valid_dyn_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Y_address0,
        Y_ce0,
        Y_we0,
        Y_d0
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] Y_address0;
output   Y_ce0;
output   Y_we0;
output  [31:0] Y_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Y_ce0;
reg Y_we0;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] X06_address0;
reg    X06_ce0;
wire   [31:0] X06_q0;
wire   [12:0] ConvW2_address0;
reg    ConvW2_ce0;
wire   [31:0] ConvW2_q0;
wire   [7:0] t_fu_167_p2;
reg   [7:0] t_reg_289;
wire    ap_CS_fsm_state2;
wire   [12:0] shl_ln_fu_173_p3;
reg   [12:0] shl_ln_reg_294;
wire   [0:0] icmp_ln50_fu_161_p2;
wire   [12:0] zext_ln51_fu_181_p1;
reg   [12:0] zext_ln51_reg_299;
wire    ap_CS_fsm_state3;
wire   [5:0] f_fu_191_p2;
reg   [5:0] f_reg_308;
wire   [2:0] k_fu_203_p2;
reg   [2:0] k_reg_316;
wire    ap_CS_fsm_state4;
wire   [12:0] shl_ln8_fu_219_p3;
reg   [12:0] shl_ln8_reg_321;
wire   [0:0] icmp_ln53_fu_197_p2;
wire   [5:0] e_fu_242_p2;
reg   [5:0] e_reg_329;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln56_fu_236_p2;
reg   [31:0] X06_load_reg_344;
wire    ap_CS_fsm_state6;
reg   [31:0] ConvW2_load_reg_349;
wire   [31:0] grp_fu_157_p2;
reg   [31:0] tmp_reg_354;
wire    ap_CS_fsm_state10;
wire   [31:0] grp_fu_152_p2;
wire    ap_CS_fsm_state15;
reg   [7:0] t_0_reg_81;
wire   [0:0] icmp_ln51_fu_185_p2;
reg   [5:0] f_0_reg_93;
reg   [31:0] acc_0_reg_104;
reg   [2:0] k_0_reg_117;
reg   [31:0] acc_1_reg_129;
reg   [5:0] e_0_reg_141;
wire   [63:0] zext_ln58_fu_231_p1;
wire   [63:0] zext_ln56_5_fu_257_p1;
wire   [63:0] zext_ln56_6_fu_281_p1;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state7;
wire   [7:0] zext_ln54_fu_209_p1;
wire   [7:0] add_ln54_fu_213_p2;
wire   [12:0] add_ln58_fu_227_p2;
wire   [12:0] zext_ln56_fu_248_p1;
wire   [12:0] add_ln56_fu_252_p2;
wire   [4:0] trunc_ln56_fu_262_p1;
wire   [12:0] tmp1_fu_266_p4;
wire   [12:0] add_ln56_5_fu_276_p2;
reg   [14:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
end

conv1d_valid_dyn_2_X06 #(
    .DataWidth( 32 ),
    .AddressRange( 4800 ),
    .AddressWidth( 13 ))
X06_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(X06_address0),
    .ce0(X06_ce0),
    .q0(X06_q0)
);

conv1d_valid_dyn_2_ConvW2 #(
    .DataWidth( 32 ),
    .AddressRange( 7168 ),
    .AddressWidth( 13 ))
ConvW2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ConvW2_address0),
    .ce0(ConvW2_ce0),
    .q0(ConvW2_q0)
);

main_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
main_fadd_32ns_32ns_32_5_full_dsp_1_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(acc_1_reg_129),
    .din1(tmp_reg_354),
    .ce(1'b1),
    .dout(grp_fu_152_p2)
);

main_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
main_fmul_32ns_32ns_32_4_max_dsp_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(X06_load_reg_344),
    .din1(ConvW2_load_reg_349),
    .ce(1'b1),
    .dout(grp_fu_157_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_185_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        acc_0_reg_104 <= 32'd0;
    end else if (((icmp_ln56_fu_236_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_0_reg_104 <= acc_1_reg_129;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        acc_1_reg_129 <= grp_fu_152_p2;
    end else if (((icmp_ln53_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_1_reg_129 <= acc_0_reg_104;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        e_0_reg_141 <= e_reg_329;
    end else if (((icmp_ln53_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        e_0_reg_141 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln50_fu_161_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        f_0_reg_93 <= 6'd0;
    end else if (((icmp_ln53_fu_197_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        f_0_reg_93 <= f_reg_308;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_185_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        k_0_reg_117 <= 3'd0;
    end else if (((icmp_ln56_fu_236_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        k_0_reg_117 <= k_reg_316;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln51_fu_185_p2 == 1'd1))) begin
        t_0_reg_81 <= t_reg_289;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_0_reg_81 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ConvW2_load_reg_349 <= ConvW2_q0;
        X06_load_reg_344 <= X06_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        e_reg_329 <= e_fu_242_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        f_reg_308 <= f_fu_191_p2;
        zext_ln51_reg_299[5 : 0] <= zext_ln51_fu_181_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        k_reg_316 <= k_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        shl_ln8_reg_321[12 : 5] <= shl_ln8_fu_219_p3[12 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln50_fu_161_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        shl_ln_reg_294[12 : 5] <= shl_ln_fu_173_p3[12 : 5];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        t_reg_289 <= t_fu_167_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        tmp_reg_354 <= grp_fu_157_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ConvW2_ce0 = 1'b1;
    end else begin
        ConvW2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        X06_ce0 = 1'b1;
    end else begin
        X06_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Y_ce0 = 1'b1;
    end else begin
        Y_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln53_fu_197_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        Y_we0 = 1'b1;
    end else begin
        Y_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln50_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln50_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln51_fu_185_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln53_fu_197_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln56_fu_236_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ConvW2_address0 = zext_ln56_6_fu_281_p1;

assign X06_address0 = zext_ln56_5_fu_257_p1;

assign Y_address0 = zext_ln58_fu_231_p1;

assign Y_d0 = acc_0_reg_104;

assign add_ln54_fu_213_p2 = (t_0_reg_81 + zext_ln54_fu_209_p1);

assign add_ln56_5_fu_276_p2 = (zext_ln51_reg_299 + tmp1_fu_266_p4);

assign add_ln56_fu_252_p2 = (zext_ln56_fu_248_p1 + shl_ln8_reg_321);

assign add_ln58_fu_227_p2 = (shl_ln_reg_294 + zext_ln51_reg_299);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign e_fu_242_p2 = (e_0_reg_141 + 6'd1);

assign f_fu_191_p2 = (f_0_reg_93 + 6'd1);

assign icmp_ln50_fu_161_p2 = ((t_0_reg_81 == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_185_p2 = ((f_0_reg_93 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_197_p2 = ((k_0_reg_117 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_236_p2 = ((e_0_reg_141 == 6'd32) ? 1'b1 : 1'b0);

assign k_fu_203_p2 = (k_0_reg_117 + 3'd1);

assign shl_ln8_fu_219_p3 = {{add_ln54_fu_213_p2}, {5'd0}};

assign shl_ln_fu_173_p3 = {{t_0_reg_81}, {5'd0}};

assign t_fu_167_p2 = (t_0_reg_81 + 8'd1);

assign tmp1_fu_266_p4 = {{{k_0_reg_117}, {trunc_ln56_fu_262_p1}}, {5'd0}};

assign trunc_ln56_fu_262_p1 = e_0_reg_141[4:0];

assign zext_ln51_fu_181_p1 = f_0_reg_93;

assign zext_ln54_fu_209_p1 = k_0_reg_117;

assign zext_ln56_5_fu_257_p1 = add_ln56_fu_252_p2;

assign zext_ln56_6_fu_281_p1 = add_ln56_5_fu_276_p2;

assign zext_ln56_fu_248_p1 = e_0_reg_141;

assign zext_ln58_fu_231_p1 = add_ln58_fu_227_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_294[4:0] <= 5'b00000;
    zext_ln51_reg_299[12:6] <= 7'b0000000;
    shl_ln8_reg_321[4:0] <= 5'b00000;
end

endmodule //conv1d_valid_dyn_2
